### PR TITLE
Fully move to merge queues

### PR DESCRIPTION
**Pull request by 0152la**
Do the rest of the stuff needed to fully migrate to merge queues and remove old `bors` file. Also this PR will likely fix any CI issues that might have remained from merging #13.

### CODE REVIEW

**Comment by ltratt** [comment]
I think this has accidentally `rm`ed `.buildbot.sh` instead of `bors.toml`?

**Comment by 0152la** [comment]
(:

**Comment by ltratt** [comment]
Please squash.

**Comment by 0152la** [comment]
Squashed.

**Pull request merged**
